'use client'

import { useEffect, useState } from 'react'
import { apiFetch } from '../../lib/api'
import AppShell from '../../components/layout/AppShell'
import { useUi } from '../../components/ui/UiProvider'
import styles from './page.module.css'

type Settings={workspaceId:string;serviceFeePercent:number;fallbackUsdMntRate:number;fallbackRateDate:string}
type Overview={summary:{transactions:number;succeeded:number;failed:number;serviceFeesMnt:number;webhookErrors:number};payments:any[];auditLogs:any[];webhookErrors:any[];checkedAt:string}
type PrelaunchCheck={key:string;label:string;status:'READY'|'WARNING'|'ERROR';detail:string;action?:string}
type Prelaunch={overall:'READY'|'WARNING'|'ERROR';summary:{ready:number;warnings:number;errors:number;total:number};checks:PrelaunchCheck[];checkedAt:string}
const mnt=(v:number)=>Math.round(Number(v||0)).toLocaleString('mn-MN')+'₮'

export default function AdminPage(){
 const {text}=useUi()
 const statusText=(s:string)=>s==='READY'?text('Бэлэн','Ready'):s==='WARNING'?text('Анхааруулга','Warning'):text('Алдаа','Error')
 const [settings,setSettings]=useState<Settings|null>(null),[overview,setOverview]=useState<Overview|null>(null),[prelaunch,setPrelaunch]=useState<Prelaunch|null>(null),[checking,setChecking]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function load(){try{const [s,o]=await Promise.all([apiFetch<Settings>('/billing/admin/settings'),apiFetch<Overview>('/billing/admin/overview')]);setSettings(s);setOverview(o);setError('')}catch(e:any){setError(e?.message||text('Админ мэдээлэл ачаалж чадсангүй.','Could not load admin data.'))}}
 useEffect(()=>{load()},[])
 async function save(){if(!settings)return;try{await apiFetch('/billing/admin/settings',{method:'PATCH',body:JSON.stringify({serviceFeePercent:settings.serviceFeePercent,fallbackUsdMntRate:settings.fallbackUsdMntRate,fallbackRateDate:settings.fallbackRateDate})});setMessage(text('Тохиргоо хадгалагдлаа. Audit log бүртгэгдсэн.','Settings saved and written to the audit log.'));await load()}catch(e:any){setError(e?.message||text('Тохиргоо хадгалж чадсангүй.','Could not save settings.'))}}
 async function runPrelaunch(){setChecking(true);setError('');setMessage('');try{const result=await apiFetch<Prelaunch>('/system/prelaunch');setPrelaunch(result);setMessage(result.overall==='READY'?text('Production launch-д бүх critical шалгалт бэлэн байна.','All critical production checks are ready.'):result.overall==='WARNING'?text('Critical error алга. Анхааруулгуудыг launch-аас өмнө шалгана уу.','No critical errors. Review warnings before launch.'):text('Production launch блоклогдсон. Алдаануудыг засна уу.','Production launch is blocked. Resolve the errors first.'))}catch(e:any){setError(e?.message||text('Pre-Launch System Check ажиллуулж чадсангүй.','Could not run the Pre-Launch System Check.'))}finally{setChecking(false)}}
 return <AppShell title={text('Админ консол','Admin Console')} subtitle={text('Шимтгэл, ханш, төлбөр, webhook, audit log болон production readiness.','Fees, exchange rates, payments, webhooks, audit logs and production readiness.')}>
  {error&&<div className={styles.notice+' '+styles.error}>{error}</div>}{message&&<div className={styles.notice}>{message}</div>}
  <section className={styles.card+' '+styles.prelaunch}><div className={styles.cardHead}><div><span>PRODUCTION READINESS</span><h2>Pre-Launch System Check</h2><p>{text('Meta API/OAuth, Supabase, төлбөрийн backend, webhook, FX source болон production URL-уудыг нэг дор шалгана.','Checks Meta API/OAuth, Supabase, billing backend, webhooks, FX source and production URLs in one place.')}</p></div><button className={styles.save} onClick={runPrelaunch} disabled={checking}>{checking?text('Шалгаж байна…','Checking…'):text('Бүх системийг шалгах','Run system check')}</button></div>
  {prelaunch&&<><div className={styles.preStats}><Metric label={text('Ерөнхий','Overall')} value={statusText(prelaunch.overall)} tone={prelaunch.overall}/><Metric label={text('Бэлэн','Ready')} value={String(prelaunch.summary.ready)}/><Metric label={text('Анхааруулга','Warnings')} value={String(prelaunch.summary.warnings)}/><Metric label={text('Алдаа','Errors')} value={String(prelaunch.summary.errors)}/></div><div className={styles.checks}>{prelaunch.checks.map(c=><div key={c.key} className={styles.check}><b data-status={c.status}>{statusText(c.status)}</b><strong>{c.label}</strong><div>{c.detail}{c.action&&<small>→ {c.action}</small>}</div></div>)}</div><p className={styles.checked}>{text('Сүүлд шалгасан','Last checked')}: {new Date(prelaunch.checkedAt).toLocaleString()} · {text('үр дүн audit log-д бүртгэгдэнэ.','results are recorded in the audit log.')}</p></>}
  </section>

  <div className={styles.stats}><Metric label={text('Гүйлгээ','Transactions')} value={String(overview?.summary.transactions??'—')}/><Metric label={text('Амжилттай','Succeeded')} value={String(overview?.summary.succeeded??'—')}/><Metric label={text('Амжилтгүй','Failed')} value={String(overview?.summary.failed??'—')}/><Metric label={text('Авсан шимтгэл','Collected fees')} value={overview?mnt(overview.summary.serviceFeesMnt):'—'}/></div>

  <div className={styles.grid}>
   <section className={styles.card}><h2>{text('Төлбөрийн тохиргоо','Billing settings')}</h2><label className={styles.field}><span>{text('Үйлчилгээний шимтгэл (%)','Service fee (%)')}</span><input type="number" min="0" max="100" step="0.1" value={settings?.serviceFeePercent??''} onChange={e=>settings&&setSettings({...settings,serviceFeePercent:Number(e.target.value)})}/></label><label className={styles.field}><span>{text('Fallback USD/MNT ханш','Fallback USD/MNT rate')}</span><input type="number" min="1" step="0.01" value={settings?.fallbackUsdMntRate??''} onChange={e=>settings&&setSettings({...settings,fallbackUsdMntRate:Number(e.target.value)})}/></label><label className={styles.field}><span>{text('Fallback ханшийн огноо','Fallback rate date')}</span><input type="date" value={settings?.fallbackRateDate??''} onChange={e=>settings&&setSettings({...settings,fallbackRateDate:e.target.value})}/></label><button className={styles.save} onClick={save}>{text('Хадгалах','Save')}</button><div className={styles.hint}>{text('Зөвхөн workspace owner/admin эрхтэй хэрэглэгч өөрчилнө.','Only workspace owners/admins can change these settings.')}</div></section>
   <DataTable title={text('Сүүлийн гүйлгээ','Recent transactions')} headers={[text('Огноо','Date'),'USD',text('Шимтгэл','Fee'),text('Төлөв','Status')]} empty={text('Одоогоор мэдээлэл алга.','No data yet.')} rows={(overview?.payments||[]).map(p=>[new Date(p.created_at).toLocaleString(),'$'+Number(p.meta_budget_usd).toFixed(2),mnt(p.service_fee_mnt),String(p.wire_status)+(p.failure_reason?' · '+p.failure_reason:'')])}/>
   <DataTable title="Webhook monitoring" headers={['Event','Attempt','Error']} empty={text('Одоогоор мэдээлэл алга.','No data yet.')} rows={(overview?.webhookErrors||[]).map(e=>[String(e.event_type)+' '+String(e.payment_intent_id||''),String(e.attempt_count),e.last_error||'—'])}/>
   <DataTable title="Audit log" headers={[text('Огноо','Date'),'Action','Entity']} empty={text('Одоогоор мэдээлэл алга.','No data yet.')} rows={(overview?.auditLogs||[]).map(a=>[new Date(a.created_at).toLocaleString(),a.action,String(a.entity_type||'—')+' · '+String(a.entity_id||'')])}/>
  </div>
 </AppShell>
}
function Metric({label,value,tone}:{label:string;value:string;tone?:string}){return <div className={styles.stat}><span>{label}</span><b data-tone={tone}>{value}</b></div>}
function DataTable({title,headers,rows,empty}:{title:string;headers:string[];rows:string[][];empty:string}){return <section className={styles.card}><h2>{title}</h2><div className={styles.scroll}><table className={styles.table}><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>):<tr><td colSpan={headers.length}>{empty}</td></tr>}</tbody></table></div></section>}
