'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Facebook, Image as ImageIcon, Rocket, ShieldCheck } from 'lucide-react'
import AppShell from '../../../components/layout/AppShell'
import { apiFetch } from '../../../lib/api'
import styles from '../../manager.module.css'

type Page={id:string;name:string}
type AdAccount={id:string;account_id:string;name:string;currency:string;timezone_name:string;account_status:number}
type Post={id:string;message?:string;created_time?:string;full_picture?:string}
type Readiness={connected:boolean;ready:boolean;accounts:Array<{id:string;accountId:string;ready:boolean;paymentFailed:boolean;userMessage:string}>}
type Created={campaignId:string;adSetId:string;creativeId:string;adId:string}
const objectives=[['OUTCOME_AWARENESS','Таниулах'],['OUTCOME_TRAFFIC','Хандалт'],['OUTCOME_ENGAGEMENT','Оролцоо'],['OUTCOME_LEADS','Лийд'],['OUTCOME_SALES','Борлуулалт']] as const
const csv=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean)

export default function BoostCreatePage(){
 const [step,setStep]=useState(1),[pages,setPages]=useState<Page[]>([]),[accounts,setAccounts]=useState<AdAccount[]>([]),[posts,setPosts]=useState<Post[]>([])
 const [pageId,setPageId]=useState(''),[accountId,setAccountId]=useState(''),[postId,setPostId]=useState('')
 const [objective,setObjective]=useState('OUTCOME_ENGAGEMENT'),[name,setName]=useState(`RAINY Boost ${new Date().toLocaleDateString('mn-MN')}`),[specialCategory,setSpecialCategory]=useState('NONE')
 const [countries,setCountries]=useState('MN'),[ageMin,setAgeMin]=useState(18),[ageMax,setAgeMax]=useState(65),[gender,setGender]=useState('0'),[placement,setPlacement]=useState('AUTO'),[device,setDevice]=useState('ALL')
 const [interestIds,setInterestIds]=useState(''),[customAudienceIds,setCustomAudienceIds]=useState(''),[excludedAudienceIds,setExcludedAudienceIds]=useState('')
 const [dailyBudget,setDailyBudget]=useState(10000),[days,setDays]=useState(7),[optimizationOverride,setOptimizationOverride]=useState('AUTO')
 const [loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[activating,setActivating]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState<Created|null>(null),[active,setActive]=useState(false),[approveSpend,setApproveSpend]=useState(false)
 const [readiness,setReadiness]=useState<Readiness|null>(null)
 useEffect(()=>{(async()=>{try{const [p,a,r]=await Promise.all([apiFetch<any>('/meta/pages'),apiFetch<any>('/meta/ad-accounts'),apiFetch<Readiness>('/meta/readiness')]);const pp=p?.data||[],aa=a?.data||[];setPages(pp);setAccounts(aa);setReadiness(r);if(pp[0])setPageId(pp[0].id);if(aa[0])setAccountId(aa[0].account_id||aa[0].id)}catch(e:any){setError(e?.message||'Meta мэдээлэл ачаалж чадсангүй.')}finally{setLoading(false)}})()},[])
 useEffect(()=>{if(!pageId)return;setPosts([]);setPostId('');apiFetch<any>(`/meta/pages/${encodeURIComponent(pageId)}/posts`).then(r=>{const d=r?.data||[];setPosts(d);if(d[0])setPostId(d[0].id)}).catch((e:any)=>setError(e?.message||'Постууд авч чадсангүй.'))},[pageId])
 const account=accounts.find(a=>(a.account_id||a.id)===accountId),post=posts.find(p=>p.id===postId)
 const defaultOptimization=useMemo(()=>objective==='OUTCOME_TRAFFIC'?'LINK_CLICKS':objective==='OUTCOME_AWARENESS'?'REACH':objective==='OUTCOME_LEADS'?'LEAD_GENERATION':objective==='OUTCOME_SALES'?'OFFSITE_CONVERSIONS':'POST_ENGAGEMENT',[objective])
 const optimization=optimizationOverride==='AUTO'?defaultOptimization:optimizationOverride
 const steps=['Пост','Зорилго','Аудитори','Төсөв','Хугацаа','Шалгах','Үүсгэх']
 function canNext(){if(step===1)return!!(pageId&&accountId&&postId);if(step===2)return!!(name&&objective);if(step===3)return ageMin>=18&&ageMax>=ageMin&&csv(countries).length>0;if(step===4)return dailyBudget>0;if(step===5)return days>=1;return true}
 function targeting(){const t:any={geo_locations:{countries:csv(countries)},age_min:ageMin,age_max:ageMax};if(gender!=='0')t.genders=[Number(gender)];if(placement!=='AUTO')t.publisher_platforms=placement==='FACEBOOK'?['facebook']:placement==='INSTAGRAM'?['instagram']:['facebook','instagram'];if(device!=='ALL')t.device_platforms=[device.toLowerCase()];const interests=csv(interestIds);if(interests.length)t.interests=interests.map(id=>({id}));const ca=csv(customAudienceIds);if(ca.length)t.custom_audiences=ca.map(id=>({id}));const ex=csv(excludedAudienceIds);if(ex.length)t.excluded_custom_audiences=ex.map(id=>({id}));return t}
 async function createAll(){if(!readiness?.ready){setError('Ad Account/payment readiness бэлэн биш байна.');return}if(!account||!post)return;setCreating(true);setError('');try{const campaign=await apiFetch<any>(`/meta/ad-accounts/${encodeURIComponent(accountId)}/campaigns`,{method:'POST',body:JSON.stringify({name,objective,specialAdCategories:specialCategory==='NONE'?[]:[specialCategory]})});const budgetMinor=account.currency==='MNT'?Math.round(dailyBudget):Math.round(dailyBudget*100);const start=new Date(Date.now()+5*60000),end=new Date(start.getTime()+days*86400000);const adset=await apiFetch<any>(`/meta/ad-accounts/${encodeURIComponent(accountId)}/adsets`,{method:'POST',body:JSON.stringify({name:`${name} · Ad Set`,campaignId:campaign.id,dailyBudget:budgetMinor,billingEvent:'IMPRESSIONS',optimizationGoal:optimization,bidStrategy:'LOWEST_COST_WITHOUT_CAP',targeting:targeting(),startTime:start.toISOString(),endTime:end.toISOString()})});const creative=await apiFetch<any>(`/meta/ad-accounts/${encodeURIComponent(accountId)}/creatives/existing-post`,{method:'POST',body:JSON.stringify({name:`${name} · Creative`,objectStoryId:post.id})});const ad=await apiFetch<any>(`/meta/ad-accounts/${encodeURIComponent(accountId)}/ads`,{method:'POST',body:JSON.stringify({name:`${name} · Ad`,adSetId:adset.id,creativeId:creative.id})});setCreated({campaignId:campaign.id,adSetId:adset.id,creativeId:creative.id,adId:ad.id});setStep(7)}catch(e:any){setError(e?.message||'Meta campaign үүсгэх үед алдаа гарлаа.')}finally{setCreating(false)}}
 async function activateAll(){if(!created||!approveSpend)return;setActivating(true);setError('');try{for(const id of [created.adId,created.adSetId,created.campaignId])await apiFetch(`/meta/objects/${encodeURIComponent(id)}/status`,{method:'POST',body:JSON.stringify({status:'ACTIVE'})});setActive(true)}catch(e:any){setError(e?.message||'Идэвхжүүлэх үед Meta readiness/payment guard блоклолоо.')}finally{setActivating(false)}}
 if(loading)return <AppShell title="Boost үүсгэх"><div className={styles.card}><div className={styles.spinner}/><p className={styles.muted}>Meta Page, Ad Account, readiness ачаалж байна…</p></div></AppShell>
 return <AppShell title="Boost үүсгэх" subtitle="Page → Post → Objective → Audience → Budget → Schedule → PAUSED Ad → хэрэглэгчийн баталгаатай ACTIVE">
  <div className={styles.steps}>{steps.map((x,i)=><div key={x} className={`${styles.step} ${step===i+1?styles.stepActive:''} ${step>i+1?styles.stepDone:''}`}><b>{step>i+1?'✓ ':''}{i+1}. {x}</b><small>{step===i+1?'Одоогийн алхам':step>i+1?'Дууссан':'Хүлээгдэж байна'}</small></div>)}</div>
  {error&&<div className={styles.error}>{error}</div>}{!readiness?.ready&&<div className={styles.warning}>Facebook/Ad Account/payment readiness бүрэн биш. <a href="/facebook">Readiness шалгах →</a></div>}
  <div className={styles.grid2} style={{marginTop:14}}><section className={styles.card}>
   {step===1&&<div className={styles.grid}><h2>Page, Ad Account, пост</h2><div className={styles.fields2}><label className={styles.field}><span>Facebook Page</span><select value={pageId} onChange={e=>setPageId(e.target.value)}>{pages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className={styles.field}><span>Meta Ad Account</span><select value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.account_id||a.id}>{a.name} · {a.currency}</option>)}</select></label></div>{posts.length?<div className={styles.postGrid}>{posts.map(p=><button key={p.id} className={`${styles.post} ${postId===p.id?styles.postSelected:''}`} onClick={()=>setPostId(p.id)}>{p.full_picture?<img src={p.full_picture} alt="Пост"/>:<div style={{height:125,display:'grid',placeItems:'center'}}><ImageIcon/></div>}<div><b>{(p.message||'Зурагт пост').slice(0,100)}</b><small>{p.created_time?new Date(p.created_time).toLocaleString('mn-MN'):''}</small></div></button>)}</div>:<div className={styles.empty}>Пост олдсонгүй.</div>}</div>}
   {step===2&&<div className={styles.grid}><h2>Campaign тохиргоо</h2><label className={styles.field}><span>Кампайны нэр</span><input value={name} onChange={e=>setName(e.target.value)}/></label><div className={styles.grid3}>{objectives.map(([v,l])=><button key={v} className={objective===v?styles.primary:styles.secondary} onClick={()=>setObjective(v)}>{l}</button>)}</div><div className={styles.fields2}><label className={styles.field}><span>Special Ad Category</span><select value={specialCategory} onChange={e=>setSpecialCategory(e.target.value)}><option value="NONE">Байхгүй</option><option value="HOUSING">Housing</option><option value="EMPLOYMENT">Employment</option><option value="CREDIT">Credit</option><option value="ISSUES_ELECTIONS_POLITICS">Issues / Elections / Politics</option></select></label><label className={styles.field}><span>Optimization goal</span><select value={optimizationOverride} onChange={e=>setOptimizationOverride(e.target.value)}><option value="AUTO">Автомат ({defaultOptimization})</option><option value="REACH">REACH</option><option value="LINK_CLICKS">LINK_CLICKS</option><option value="POST_ENGAGEMENT">POST_ENGAGEMENT</option><option value="LEAD_GENERATION">LEAD_GENERATION</option><option value="OFFSITE_CONVERSIONS">OFFSITE_CONVERSIONS</option></select></label></div><div className={styles.notice}>Buying type: AUCTION · Billing event: IMPRESSIONS · Bid strategy: LOWEST_COST_WITHOUT_CAP</div></div>}
   {step===3&&<div className={styles.grid}><h2>Audience & Placement</h2><div className={styles.fields3}><label className={styles.field}><span>Улсын code (таслалаар)</span><input value={countries} onChange={e=>setCountries(e.target.value.toUpperCase())} placeholder="MN"/></label><label className={styles.field}><span>Доод нас</span><input type="number" min="18" max="65" value={ageMin} onChange={e=>setAgeMin(Number(e.target.value))}/></label><label className={styles.field}><span>Дээд нас</span><input type="number" min="18" max="65" value={ageMax} onChange={e=>setAgeMax(Number(e.target.value))}/></label></div><div className={styles.fields3}><label className={styles.field}><span>Хүйс</span><select value={gender} onChange={e=>setGender(e.target.value)}><option value="0">Бүгд</option><option value="1">Эрэгтэй</option><option value="2">Эмэгтэй</option></select></label><label className={styles.field}><span>Publisher placement</span><select value={placement} onChange={e=>setPlacement(e.target.value)}><option value="AUTO">Advantage+ / Automatic</option><option value="BOTH">Facebook + Instagram</option><option value="FACEBOOK">Facebook</option><option value="INSTAGRAM">Instagram</option></select></label><label className={styles.field}><span>Device</span><select value={device} onChange={e=>setDevice(e.target.value)}><option value="ALL">Бүх төхөөрөмж</option><option value="MOBILE">Mobile</option><option value="DESKTOP">Desktop</option></select></label></div><label className={styles.field}><span>Detailed interests — Meta Interest ID-ууд</span><input value={interestIds} onChange={e=>setInterestIds(e.target.value)} placeholder="6003139266461, 6003384248805"/></label><div className={styles.fields2}><label className={styles.field}><span>Custom Audience ID</span><input value={customAudienceIds} onChange={e=>setCustomAudienceIds(e.target.value)} placeholder="ID-ууд таслалаар"/></label><label className={styles.field}><span>Excluded Custom Audience ID</span><input value={excludedAudienceIds} onChange={e=>setExcludedAudienceIds(e.target.value)} placeholder="ID-ууд таслалаар"/></label></div>{specialCategory!=='NONE'&&<div className={styles.warning}>Special Ad Category сонгосон үед Meta audience targeting-ийн зарим сонголтыг өөрөө хязгаарлаж болно.</div>}</div>}
   {step===4&&<div className={styles.grid}><h2>Төсөв</h2><label className={styles.field}><span>{account?.currency||'Currency'} / өдөр</span><input type="number" min="1" value={dailyBudget} onChange={e=>setDailyBudget(Number(e.target.value)||1)}/></label><div className={styles.notice}>Ad Set daily budget · {account?.name||'—'} · {account?.currency||'—'}</div></div>}
   {step===5&&<div className={styles.grid}><h2>Schedule</h2><label className={styles.field}><span>Ажиллах хоног</span><input type="number" min="1" max="90" value={days} onChange={e=>setDays(Number(e.target.value)||1)}/></label><div className={styles.summary}><div><span>Start</span><b>Одоогоос ~5 минутын дараа</b></div><div><span>End</span><b>{new Date(Date.now()+days*86400000).toLocaleDateString('mn-MN')}</b></div></div></div>}
   {step===6&&<div className={styles.grid}><h2>Эцсийн шалгалт</h2><div className={styles.summary}><div><span>Page / Post</span><b>{pages.find(p=>p.id===pageId)?.name||'—'} · {postId}</b></div><div><span>Ad Account</span><b>{account?.name||'—'} · {account?.currency}</b></div><div><span>Objective</span><b>{objective} / {optimization}</b></div><div><span>Special category</span><b>{specialCategory}</b></div><div><span>Audience</span><b>{countries} · {ageMin}–{ageMax} · {gender==='0'?'Бүгд':gender==='1'?'Эрэгтэй':'Эмэгтэй'}</b></div><div><span>Placement</span><b>{placement} · {device}</b></div><div><span>Detailed targeting</span><b>{csv(interestIds).length} interests · {csv(customAudienceIds).length} custom audiences</b></div><div><span>Budget</span><b>{dailyBudget.toLocaleString('mn-MN')} {account?.currency}/өдөр · {days} хоног</b></div><div><span>Safety</span><b>Campaign + Ad Set + Ad = PAUSED</b></div></div><button className={styles.primary} onClick={()=>setStep(7)} disabled={!readiness?.ready}><ShieldCheck size={16}/> Үүсгэх алхам руу</button></div>}
   {step===7&&<div className={styles.grid}><h2>{active?'Boost идэвхтэй':created?'Boost PAUSED байдлаар үүслээ':'Meta дээр үүсгэх'}</h2>{created?<><div className={active?styles.success:styles.warning}>{active?'Campaign + Ad Set + Ad ACTIVE боллоо. Meta delivery эхлэх боломжтой.':'Campaign, Ad Set, Creative, Ad үүслээ. Одоогоор мөнгө зарцуулахгүй.'}</div><div className={styles.summary}><div><span>Campaign</span><b>{created.campaignId}</b></div><div><span>Ad Set</span><b>{created.adSetId}</b></div><div><span>Creative</span><b>{created.creativeId}</b></div><div><span>Ad</span><b>{created.adId}</b></div></div>{!active&&<><label style={{display:'flex',gap:10,alignItems:'flex-start',fontSize:11,lineHeight:1.5}}><input type="checkbox" checked={approveSpend} onChange={e=>setApproveSpend(e.target.checked)} style={{marginTop:2}}/><span>Би энэ зарыг ACTIVE болгож, Meta зарын төлбөр миний Ad Account payment method-оос суутгагдаж болохыг зөвшөөрч байна.</span></label><button className={styles.primary} onClick={activateAll} disabled={!approveSpend||activating}>{activating?'Payment readiness дахин шалгаж байна…':'Би баталж байна — Boost идэвхжүүлэх'}</button></>}<div className={styles.actions}><a className={styles.secondary} href="/campaigns"><Rocket size={16}/> Кампанит ажил</a><a className={styles.secondary} href="/analytics">Аналитик</a></div></>:<><div className={styles.warning}>Meta API дээр бодит объектууд үүснэ, гэхдээ бүгд PAUSED. Үүсгэсний дараа тусдаа баталгаажуулалтаар ACTIVE болгоно.</div><button className={styles.primary} onClick={createAll} disabled={creating||!readiness?.ready}>{creating?'Meta дээр үүсгэж байна…':'PAUSED Boost үүсгэх'}</button></>}</div>}
   <div className={styles.toolbar} style={{marginTop:20,marginBottom:0}}><button className={styles.secondary} onClick={()=>setStep(s=>Math.max(1,s-1))} disabled={step===1||!!created}><ArrowLeft size={15}/> Буцах</button>{step<6&&<button className={styles.primary} onClick={()=>canNext()&&setStep(s=>s+1)} disabled={!canNext()}>Үргэлжлүүлэх <ArrowRight size={15}/></button>}</div>
  </section><aside className={styles.preview}><h3>Live ad preview</h3><p className={styles.muted}>Сонгосон existing Page post.</p><div className={styles.adMock}><div className={styles.adHead}><div className={styles.avatar}><Facebook size={15}/></div><div><b>{pages.find(p=>p.id===pageId)?.name||'Facebook Page'}</b><small>Sponsored</small></div></div>{post?.full_picture?<img src={post.full_picture} alt="Preview"/>:<div style={{height:210,display:'grid',placeItems:'center'}}><ImageIcon/></div>}<div className={styles.adCopy}><b>{(post?.message||'Сонгосон пост энд харагдана.').slice(0,90)}</b><p>{objective.replace('OUTCOME_','')} · {dailyBudget.toLocaleString('mn-MN')} {account?.currency||''}/өдөр</p></div></div></aside></div>
 </AppShell>
}
