'use client'

import { useEffect, useMemo, useState } from 'react'
import { CreditCard, RefreshCw, ShieldCheck } from 'lucide-react'
import AppShell from '../../components/layout/AppShell'
import { useUi } from '../../components/ui/UiProvider'
import { apiFetch } from '../../lib/api'
import styles from '../manager.module.css'

type AdsQuote={adBudgetMnt:number;serviceFeePercent:number;serviceFeeMnt:number;totalPayableMnt:number;dailyBudgetMnt:number}
type FxQuote={fx:{rate:number;source:string;rateDate:string}}
type Tx={id:string;receipt_number?:string;meta_budget_usd:number;service_fee_mnt:number;wire_status:string;created_at:string}
const mnt=(v:number)=>Math.round(Number(v||0)).toLocaleString('mn-MN')+'₮'

export default function PaymentsPage(){
 const {text}=useUi()
 const [budget,setBudget]=useState(300000),[duration,setDuration]=useState(7),[quote,setQuote]=useState<AdsQuote|null>(null),[fx,setFx]=useState<FxQuote|null>(null),[history,setHistory]=useState<Tx[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const budgetUsd=useMemo(()=>fx?.fx.rate?budget/fx.fx.rate:0,[budget,fx])
 async function load(){try{const [q,rate,h]=await Promise.all([apiFetch<AdsQuote>('/ads/quote',{method:'POST',body:JSON.stringify({channels:['facebook','instagram','google','youtube','tiktok','x'],objective:'traffic',totalBudgetMnt:budget,durationDays:duration,audience:{country:'MN',ageMin:18,ageMax:65}})}),apiFetch<FxQuote>('/billing/quote?usd=1'),apiFetch<Tx[]>('/billing/history?limit=10')]);setQuote(q);setFx(rate);setHistory(h);setError('')}catch(e:any){setError(e?.message||text('Төлбөрийн мэдээлэл ачаалж чадсангүй.','Could not load billing data.'))}}
 useEffect(()=>{const t=setTimeout(load,220);return()=>clearTimeout(t)},[budget,duration])
 async function checkout(){if(!budgetUsd)return;setLoading(true);setError('');try{const r=await apiFetch<{checkoutUrl:string}>('/billing/fee-checkout',{method:'POST',body:JSON.stringify({metaBudgetUsd:Number(budgetUsd.toFixed(2))})});if(!r.checkoutUrl)throw new Error(text('QPay checkout URL олдсонгүй.','QPay checkout URL not returned.'));window.location.assign(r.checkoutUrl)}catch(e:any){setError(e?.message||text('Төлбөр эхлүүлж чадсангүй.','Could not start checkout.'));setLoading(false)}}
 return <AppShell title={text('Төлбөр ба төсөв','Billing & budget')} subtitle={text('MNT төсөв, platform fee болон provider settlement-ийг тусад нь ойлгомжтой харуулна.','Keep MNT budget, platform fee and provider settlement clearly separated.')}>
  <div className={styles.grid2}><section className={styles.card}><div className={styles.toolbar}><div><h2>{text('Campaign төсөв','Campaign budget')}</h2><p className={styles.muted}>{text('Ad spend + BOOST.MN service fee. Provider ad-spend settlement нь provider contract иртэл тусдаа байна.','Ad spend + BOOST.MN service fee. Provider ad-spend settlement remains separate until the provider commercial setup is finalized.')}</p></div><ShieldCheck color="var(--primary)"/></div><div className={styles.fields2}><label className={styles.field}><span>{text('Нийт рекламын төсөв (MNT)','Total ad budget (MNT)')}</span><input type="number" min="10000" step="10000" value={budget} onChange={e=>setBudget(Math.max(10000,Number(e.target.value)||10000))}/></label><label className={styles.field}><span>{text('Хугацаа','Duration')}</span><select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[3,5,7,14,30].map(d=><option key={d} value={d}>{d} {text('хоног','days')}</option>)}</select></label></div>{quote&&<div className={styles.summary} style={{marginTop:14}}><div><span>Ad budget</span><b>{mnt(quote.adBudgetMnt)}</b></div><div><span>Service fee ({quote.serviceFeePercent}%)</span><b>{mnt(quote.serviceFeeMnt)}</b></div><div><span>{text('Нийт төлбөрийн тооцоо','Total estimate')}</span><b>{mnt(quote.totalPayableMnt)}</b></div><div><span>{text('Өдрийн дундаж','Daily average')}</span><b>{mnt(quote.dailyBudgetMnt)}</b></div></div>}<button className={styles.primary} style={{width:'100%',marginTop:16}} onClick={checkout} disabled={loading||!quote||!budgetUsd}><CreditCard size={16}/>{loading?text('QPay нээж байна…','Opening QPay…'):text('Platform fee-г QPay-аар төлөх','Pay platform fee with QPay')}</button>{error&&<div className={styles.error} style={{marginTop:12}}>{error}</div>}<div className={styles.notice} style={{marginTop:12}}>{text('QPay checkout нь BOOST.MN үйлчилгээний шимтгэлийг төлнө. Advertising provider-ийн media spend settlement энэ төлбөрт орохгүй.','QPay checkout pays the BOOST.MN service fee only. Advertising-provider media-spend settlement is not included in this payment.')}</div></section>
   <aside className={styles.card}><h3>{text('Төлбөрийн бүтэц','Billing structure')}</h3><div className={styles.summary} style={{marginTop:12}}><div><span>Campaign budget</span><b>{quote?mnt(quote.adBudgetMnt):'—'}</b></div><div><span>BOOST.MN fee</span><b>{quote?mnt(quote.serviceFeeMnt):'—'}</b></div><div><span>Provider settlement</span><b>{text('Хүлээгдэж байна','Pending')}</b></div><div><span>Reference FX</span><b>{fx?.fx.rate?'1 USD = '+fx.fx.rate.toLocaleString('mn-MN')+'₮':'—'}</b></div></div><a className={styles.secondary} style={{width:'100%',marginTop:14}} href="/transactions">{text('Гүйлгээ харах','View transactions')}</a></aside></div>
  <section className={styles.card} style={{marginTop:16}}><div className={styles.toolbar}><h2>{text('Сүүлийн төлбөрүүд','Recent payments')}</h2><button className={styles.secondary} onClick={load}><RefreshCw size={14}/>{text('Шинэчлэх','Refresh')}</button></div>{history.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{text('Огноо','Date')}</th><th>Receipt</th><th>{text('Reference budget','Reference budget')}</th><th>{text('Шимтгэл','Fee')}</th><th>{text('Төлөв','Status')}</th></tr></thead><tbody>{history.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.receipt_number||'—'}</td><td>{'$'+Number(x.meta_budget_usd).toFixed(2)}</td><td>{mnt(x.service_fee_mnt)}</td><td><span className={styles.badge+' '+(x.wire_status==='succeeded'?styles.good:['failed','canceled'].includes(x.wire_status)?styles.bad:styles.warn)}>{x.wire_status}</span></td></tr>)}</tbody></table></div>:<div className={styles.empty}>{text('Одоогоор төлбөрийн түүх алга.','No payment history yet.')}</div>}</section>
 </AppShell>
}
