'use client'

import { useEffect, useMemo, useState } from 'react'
import { CirclePlus, Eye, Pause, Play, RefreshCw } from 'lucide-react'
import AppShell from '../../components/layout/AppShell'
import { useUi } from '../../components/ui/UiProvider'
import { apiFetch } from '../../lib/api'
import styles from '../manager.module.css'

type Account={id:string;account_id:string;name:string;currency:string}
type Campaign={id:string;name:string;objective:string;status:string;effective_status:string;daily_budget?:string;lifetime_budget?:string;created_time?:string}
type Draft={campaign?:{name?:string;objective?:string;channels?:string[];totalBudgetMnt?:number};createdAt?:string;submitReady?:boolean}

export default function CampaignsPage(){
 const {text}=useUi()
 const [accounts,setAccounts]=useState<Account[]>([]),[accountId,setAccountId]=useState(''),[rows,setRows]=useState<Campaign[]>([]),[draft,setDraft]=useState<Draft|null>(null),[filter,setFilter]=useState('ALL'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 async function loadAccounts(){try{const r=await apiFetch<any>('/meta/ad-accounts');const data=r?.data||[];setAccounts(data);setAccountId(x=>x||data[0]?.account_id||data[0]?.id||'');if(!data.length)setLoading(false)}catch(e:any){setError(e?.message||text('Meta Ad Account авч чадсангүй.','Could not load Meta Ad Accounts.'));setLoading(false)}}
 async function loadCampaigns(id=accountId){if(!id)return;setLoading(true);setError('');try{const r=await apiFetch<any>('/meta/ad-accounts/'+encodeURIComponent(id)+'/campaigns');setRows(r?.data||[])}catch(e:any){setError(e?.message||text('Кампанит ажлууд ачаалж чадсангүй.','Could not load campaigns.'))}finally{setLoading(false)}}
 useEffect(()=>{setQuery(new URLSearchParams(window.location.search).get('q')||'');try{setDraft(JSON.parse(localStorage.getItem('boost_last_campaign_preview')||'null'))}catch{}loadAccounts()},[])
 useEffect(()=>{if(accountId)loadCampaigns(accountId)},[accountId])
 async function setStatus(c:Campaign,status:'ACTIVE'|'PAUSED'){setBusy(c.id);setError('');try{await apiFetch('/meta/objects/'+encodeURIComponent(c.id)+'/status',{method:'POST',body:JSON.stringify({status})});await loadCampaigns()}catch(e:any){setError(e?.message||text('Төлөв өөрчилж чадсангүй.','Could not update status.'))}finally{setBusy('')}}
 const visible=useMemo(()=>rows.filter(c=>(filter==='ALL'||c.effective_status===filter||c.status===filter)&&(!query||c.name.toLowerCase().includes(query.toLowerCase()))),[rows,filter,query])
 const statusClass=(v:string)=>v==='ACTIVE'?styles.badge+' '+styles.good:['PAUSED','CAMPAIGN_PAUSED'].includes(v)?styles.badge+' '+styles.warn:styles.badge+' '+styles.neutral
 return <AppShell title={text('Кампанит ажлууд','Campaigns')} subtitle={text('Multi-channel preview болон Meta direct live campaign-уудаа нэг дор хяна.','Review multi-channel previews and live Meta campaigns in one place.')}>
  {draft?.campaign&&<section className={styles.card} style={{marginBottom:14}}><div className={styles.toolbar}><div><h2>{text('Сүүлийн multi-channel preview','Latest multi-channel preview')}</h2><p className={styles.muted}>{draft.campaign.channels?.join(' · ')} · {draft.campaign.objective} · {draft.createdAt?new Date(draft.createdAt).toLocaleString():'—'}</p></div><div className={styles.actions}><span className={styles.badge+' '+(draft.submitReady?styles.good:styles.warn)}>{draft.submitReady?'API READY':'PREVIEW ONLY'}</span><a className={styles.primary} href="/campaigns/new"><Eye size={14}/>{text('Засах / дахин preview','Edit / preview again')}</a></div></div></section>}
  <div className={styles.card}><div className={styles.toolbar}><div className={styles.actions}><label className={styles.field} style={{minWidth:250}}><span>Meta Ad Account</span><select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">{text('Account сонгох','Select account')}</option>{accounts.map(a=><option key={a.id} value={a.account_id||a.id}>{a.name} · {a.currency}</option>)}</select></label><label className={styles.field} style={{minWidth:220}}><span>{text('Хайх','Search')}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={text('Campaign нэр...','Campaign name...')}/></label></div><div className={styles.actions}><button className={styles.secondary} onClick={()=>loadCampaigns()} disabled={!accountId}><RefreshCw size={15}/>{text('Шинэчлэх','Refresh')}</button><a className={styles.primary} href="/campaigns/new"><CirclePlus size={15}/>{text('Шинэ campaign','New campaign')}</a></div></div>
   <div className={styles.tabs}>{[['ALL',text('Бүгд','All')],['ACTIVE',text('Идэвхтэй','Active')],['PAUSED',text('Зогсоосон','Paused')],['ARCHIVED',text('Архив','Archived')]].map(([v,l])=><button key={v} className={filter===v?styles.tabActive:''} onClick={()=>setFilter(v)}>{l}</button>)}</div>
   {error&&<div className={styles.error} style={{marginTop:12}}>{error}</div>}
   {!accountId?<div className={styles.empty}>{text('Meta account холбоогүй бол multi-channel preview flow-оо үргэлжлүүлэн ашиглаж болно.','You can continue using multi-channel preview mode even without a connected Meta account.')}</div>:loading?<div className={styles.empty}><div className={styles.spinner} style={{margin:'0 auto 10px'}}/>{text('Campaign ачаалж байна…','Loading campaigns…')}</div>:visible.length?<div className={styles.tableWrap} style={{marginTop:14}}><table className={styles.table}><thead><tr><th>{text('Кампанит ажил','Campaign')}</th><th>{text('Төлөв','Status')}</th><th>{text('Зорилго','Objective')}</th><th>{text('Төсөв','Budget')}</th><th>{text('Үүссэн','Created')}</th><th>{text('Үйлдэл','Action')}</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><b>{c.name}</b><div className={styles.muted}>{c.id}</div></td><td><span className={statusClass(c.effective_status||c.status)}>{c.effective_status||c.status}</span></td><td>{c.objective?.replace('OUTCOME_','')||'—'}</td><td>{c.daily_budget||c.lifetime_budget||text('Ad Set түвшинд','Ad Set level')}</td><td>{c.created_time?new Date(c.created_time).toLocaleDateString():'—'}</td><td><div className={styles.actions}>{(c.status==='ACTIVE'||c.effective_status==='ACTIVE')?<button className={styles.secondary} disabled={busy===c.id} onClick={()=>setStatus(c,'PAUSED')}><Pause size={14}/>Pause</button>:<button className={styles.primary} disabled={busy===c.id} onClick={()=>setStatus(c,'ACTIVE')}><Play size={14}/>{text('Идэвхжүүлэх','Activate')}</button>}<a className={styles.ghost} href={'/analytics?account='+encodeURIComponent(accountId)+'&campaign='+encodeURIComponent(c.id)}>{text('Тайлан','Report')}</a></div></td></tr>)}</tbody></table></div>:<div className={styles.empty}>{text('Campaign алга.','No campaigns found.')}</div>}
   <div className={styles.warning} style={{marginTop:14}}>{text('Live идэвхжүүлэлт дээр backend spend/payment guard дахин шалгана.','Backend spend/payment guards are rechecked before live activation.')}</div>
  </div>
 </AppShell>
}
