'use client'

import { useEffect, useState } from 'react'
import { ArrowRight, Check, CreditCard, ExternalLink, Facebook, Loader2, RefreshCw, ShieldCheck, WalletCards } from 'lucide-react'
import { API_BASE, apiFetch } from '../../lib/api'
import AppShell from '../../components/layout/AppShell'
import styles from './page.module.css'

type Status={configured:boolean;sessionConfigured:boolean;productionReady:boolean;graphVersion:string;redirectUri:string;tenantStorageConfigured?:boolean}
type Session={connected:boolean;profile?:{name?:string}}
type Account={id:string;accountId:string;name:string;currency:string;timezoneName:string;accountStatus:number;accountStatusLabel:string;disableReason:number;billingState:'READY'|'MISSING'|'UNKNOWN';paymentGuard:'READY'|'PAYMENT_FAILED'|'ACCOUNT_BLOCKED'|'PAYMENT_METHOD_MISSING'|'BILLING_CHECK_REQUIRED';paymentFailed:boolean;ready:boolean;userMessage:string}
type Readiness={connected:boolean;hasAdAccount:boolean;billingVisibility:boolean;ready:boolean;paymentFailed:boolean;accounts:Account[];setup:{createAdAccountUrl:string;adsManagerUrl:string;billingUrl:string};note:string}

export default function FacebookConnectionPage(){
 const [status,setStatus]=useState<Status|null>(null);const [session,setSession]=useState<Session>({connected:false});const [readiness,setReadiness]=useState<Readiness|null>(null);const [loading,setLoading]=useState(true);const [connecting,setConnecting]=useState(false);const [error,setError]=useState('')
 async function refresh(){setLoading(true);setError('');try{const [s,ss]=await Promise.all([apiFetch<Status>('/meta/status'),apiFetch<Session>('/meta/session').catch(()=>({connected:false}))]);setStatus(s);setSession(ss);if(ss.connected)setReadiness(await apiFetch<Readiness>('/meta/readiness'));else setReadiness(null)}catch(err:any){setError(err?.message||`Backend API (${API_BASE})-тай холбогдож чадсангүй.`)}finally{setLoading(false)}}
 useEffect(()=>{const p=new URLSearchParams(window.location.search);const e=p.get('error');if(e)setError(e);refresh()},[])
 async function connectFacebook(){setConnecting(true);setError('');try{const data=await apiFetch<{url:string}>('/meta/auth/url');if(!data?.url)throw new Error('Facebook Login URL олдсонгүй.');window.location.assign(data.url)}catch(err:any){setError(err?.message||'Facebook холболтыг эхлүүлж чадсангүй.');setConnecting(false)}}
 async function disconnectFacebook(){await apiFetch('/meta/logout',{method:'POST'});setSession({connected:false});setReadiness(null)}
 const appReady=Boolean(status?.productionReady);const active=readiness?.accounts.find(a=>a.ready)||readiness?.accounts.find(a=>a.paymentFailed)||readiness?.accounts.find(a=>a.accountStatus===1)||readiness?.accounts[0];const paymentFailed=Boolean(active?.paymentFailed)
 return <AppShell title="Facebook холбох" subtitle="Facebook → Ad Account → Төлбөр → Boost readiness дарааллаар автоматаар шалгана.">
  <section className={styles.hero}><div><span>FACEBOOK ADS CONNECTION</span><h2>Facebook бизнес аккаунтаа<br/><em>RAINY-тэй холбоно уу</em></h2><p>Нууц үг RAINY дээр хадгалагдахгүй. Meta-ийн OAuth урсгалаар Page, Ad Account болон шаардлагатай permission-үүдийг холбоно.</p><div className={styles.security}><ShieldCheck size={16}/> Campaign/Ad ACTIVE болохын өмнө төлбөрийн readiness дахин шалгагдана.</div></div><div className={styles.metaVisual}><Facebook size={44}/><b>{session.connected?'Холбогдсон':'Meta OAuth'}</b><small>{status?.graphVersion||'v25.0'}</small></div></section>
  {error&&<div className={styles.error}><b>Мэдээлэл ачаалж чадсангүй.</b><span>{error}</span><button onClick={refresh}>Дахин оролдох</button></div>}
  {paymentFailed&&readiness&&<section className={styles.paymentFailed}><CreditCard size={22}/><div><b>Төлбөрийн асуудал — Boost блоклогдсон</b><p>{active?.userMessage}</p></div><a href={readiness.setup.billingUrl} target="_blank" rel="noreferrer">Meta Billing нээх <ExternalLink size={14}/></a><button onClick={refresh}><RefreshCw size={14}/> Дахин шалгах</button></section>}
  <div className={styles.steps}><Step n="01" title="Facebook" ok={session.connected} text={session.connected?'Холбогдсон':'Холбох шаардлагатай'}/><Step n="02" title="Ad Account" ok={Boolean(readiness?.hasAdAccount)} text={readiness?.hasAdAccount?`${readiness.accounts.length} аккаунт`:'Шаардлагатай'}/><Step n="03" title="Төлбөр" ok={active?.paymentGuard==='READY'} text={paymentFailed?'Төлбөрийн асуудал':active?.paymentGuard==='READY'?'Бэлэн':'Шалгах шаардлагатай'}/><Step n="04" title="Boost" ok={Boolean(readiness?.ready)} text={paymentFailed?'Блоклогдсон':readiness?.ready?'Бэлэн':'Хүлээгдэж байна'}/></div>
  <div className={styles.grid}>
   <section className={styles.card}><div className={styles.cardHead}><span><Facebook size={20}/></span><div><small>АЛХАМ 01</small><h3>Facebook холболт</h3></div></div>{session.connected?<><div className={styles.connected}><div>{session.profile?.name?.slice(0,1).toUpperCase()||'F'}</div><p><span>Холбогдсон</span><b>{session.profile?.name||'Facebook хэрэглэгч'}</b><small>OAuth token хамгаалагдсан</small></p><Check size={19}/></div><button className={styles.secondary} onClick={disconnectFacebook}>Холболтыг салгах</button></>:<><p className={styles.muted}>Meta-ийн албан ёсны нэвтрэх цонхоор Facebook бизнес аккаунтаа холбоно.</p><button className={styles.primary} onClick={connectFacebook} disabled={!appReady||loading||connecting}>{connecting?<Loader2 className={styles.spin} size={17}/>:<Facebook size={17}/>} {connecting?'Facebook руу шилжиж байна…':'Facebook-тэй холбох'}<ArrowRight size={16}/></button></>}</section>
   <section className={styles.card}><div className={styles.cardHead}><span className={styles.green}><ShieldCheck size={20}/></span><div><small>АЛХАМ 02–04</small><h3>Ad Account readiness</h3></div></div>{!session.connected?<Empty text="Эхлээд Facebook холбоно уу."/>:loading?<Empty text="Meta Ad Account шалгаж байна…"/>:!readiness?.hasAdAccount?<Setup icon={<WalletCards size={19}/>} title="Ad Account олдсонгүй" text="Meta Business Settings дээр Ad Account үүсгээд дахин шалгана уу." href={readiness?.setup.createAdAccountUrl||'https://business.facebook.com/settings/ad-accounts'} button="Ad Account үүсгэх"/>:<div className={styles.accounts}>{readiness.accounts.map(a=><article key={a.id} className={a.paymentFailed?styles.accountError:''}><div><b>{a.name||`Ad Account ${a.accountId}`}</b><small>{a.accountId} · {a.currency} · {a.timezoneName}</small></div><span data-ready={a.ready}>{a.ready?'BOOST READY':a.paymentFailed?'PAYMENT FAILED':a.accountStatusLabel}</span><p>Төлбөр: <b>{a.paymentFailed?'Асуудалтай':a.billingState==='READY'?'Бэлэн':a.billingState==='MISSING'?'Payment method шаардлагатай':'Meta дээр баталгаажуулна'}</b></p></article>)}</div>}
   {active?.paymentFailed&&readiness&&<Setup icon={<CreditCard size={19}/>} title="Төлбөрийн асуудлаа шийднэ үү" text={active.userMessage} href={readiness.setup.billingUrl} button="Meta Billing нээх"/>}{active&&!active.paymentFailed&&active.accountStatus!==1&&readiness&&<Setup icon={<ShieldCheck size={19}/>} title={`Ad Account ${active.accountStatusLabel}`} text="Ads Manager дээр restriction, account issue эсвэл outstanding balance-аа шийднэ үү." href={readiness.setup.adsManagerUrl} button="Ads Manager нээх"/>}{active&&!active.paymentFailed&&active.accountStatus===1&&active.billingState!=='READY'&&readiness&&<Setup icon={<CreditCard size={19}/>} title="Payment method тохируулах" text={readiness.note} href={readiness.setup.billingUrl} button="Meta Billing нээх"/>}{readiness?.ready&&<div className={styles.ready}><Check size={18}/><div><b>Boost хийхэд бэлэн</b><small>ACTIVE болгохын өмнө guard дахин шалгана.</small></div><a href="/#boost">Boost үүсгэх →</a></div>}{session.connected&&!paymentFailed&&<button className={styles.primary} onClick={refresh} disabled={loading}><RefreshCw size={15}/> {loading?'Шалгаж байна…':'Дахин шалгах'}</button>}</section>
  </div>
 </AppShell>
}
function Step({n,title,ok,text}:{n:string;title:string;ok:boolean;text:string}){return <div className={styles.step}><small>{n}</small><b>{title}</b><span data-ok={ok}>{ok?'✓ ':''}{text}</span></div>}
function Empty({text}:{text:string}){return <div className={styles.empty}>{text}</div>}
function Setup({icon,title,text,href,button}:{icon:any;title:string;text:string;href:string;button:string}){return <div className={styles.setup}>{icon}<div><b>{title}</b><p>{text}</p><a href={href} target="_blank" rel="noreferrer">{button}<ExternalLink size={13}/></a></div></div>}
