'use client'

import { useEffect, useState } from 'react'
import { Languages, Moon, Save, Sun } from 'lucide-react'
import AppShell from '../../components/layout/AppShell'
import { useUi } from '../../components/ui/UiProvider'
import { supabase } from '../../lib/supabase'
import styles from '../manager.module.css'

export default function SettingsPage(){
 const {locale,theme,setLocale,setTheme,text}=useUi()
 const [tab,setTab]=useState('PROFILE'),[email,setEmail]=useState(''),[name,setName]=useState(''),[business,setBusiness]=useState(''),[notifyPayment,setNotifyPayment]=useState(true),[notifyMeta,setNotifyMeta]=useState(true),[notifyReport,setNotifyReport]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>{(async()=>{const {data,error}=await supabase.auth.getUser();if(error)setError(error.message);const u=data.user;if(u){setEmail(u.email||'');setName(String(u.user_metadata?.full_name||''));setBusiness(String(u.user_metadata?.business_name||''))}try{const p=JSON.parse(localStorage.getItem('boost_preferences')||'{}');if(typeof p.notifyPayment==='boolean')setNotifyPayment(p.notifyPayment);if(typeof p.notifyMeta==='boolean')setNotifyMeta(p.notifyMeta);if(typeof p.notifyReport==='boolean')setNotifyReport(p.notifyReport)}catch{}setLoading(false)})()},[])
 async function saveProfile(){setMessage('');setError('');const {error}=await supabase.auth.updateUser({data:{full_name:name,business_name:business}});if(error)setError(error.message);else setMessage(text('Профайл хадгалагдлаа.','Profile saved.'))}
 function saveNotifications(){localStorage.setItem('boost_preferences',JSON.stringify({notifyPayment,notifyMeta,notifyReport}));setMessage(text('Мэдэгдлийн тохиргоо хадгалагдлаа.','Notification preferences saved.'));setError('')}
 const tabs=[['PROFILE',text('Профайл','Profile')],['BUSINESS',text('Бизнес','Business')],['APPEARANCE',text('Харагдац','Appearance')],['NOTIFY',text('Мэдэгдэл','Notifications')],['PRIVACY',text('Нууцлал','Privacy')],['BILLING',text('Төлбөр','Billing')],['ADMIN',text('Админ','Admin')]]
 return <AppShell title={text('Тохиргоо','Settings')} subtitle={text('Account, бизнес, хэл, theme, мэдэгдэл болон төлбөрийн тохиргоо.','Manage account, business, language, theme, notifications and billing.')}>
  <div className={styles.tabs} style={{marginBottom:14}}>{tabs.map(([v,l])=><button key={v} className={tab===v?styles.tabActive:''} onClick={()=>{setTab(v);setMessage('');setError('')}}>{l}</button>)}</div>
  {message&&<div className={styles.success}>{message}</div>}{error&&<div className={styles.error}>{error}</div>}
  {loading?<div className={styles.card}><div className={styles.spinner}/></div>:<div className={styles.grid2} style={{marginTop:14}}><section className={styles.card}>
   {tab==='PROFILE'&&<div className={styles.grid}><h2>{text('Профайл','Profile')}</h2><label className={styles.field}><span>{text('И-мэйл','Email')}</span><input value={email} disabled/></label><label className={styles.field}><span>{text('Нэр','Name')}</span><input value={name} onChange={e=>setName(e.target.value)} placeholder={text('Таны нэр','Your name')}/></label><button className={styles.primary} onClick={saveProfile}><Save size={15}/>{text('Хадгалах','Save')}</button></div>}
   {tab==='BUSINESS'&&<div className={styles.grid}><h2>{text('Бизнес','Business')}</h2><label className={styles.field}><span>{text('Бизнесийн нэр','Business name')}</span><input value={business} onChange={e=>setBusiness(e.target.value)} placeholder="BOOST LLC"/></label><p className={styles.muted}>{text('Workspace UI дээр харагдах нэр.','Name shown across the workspace UI.')}</p><button className={styles.primary} onClick={saveProfile}><Save size={15}/>{text('Хадгалах','Save')}</button></div>}
   {tab==='APPEARANCE'&&<div className={styles.grid}><h2>{text('Хэл ба харагдац','Language & appearance')}</h2><div className={styles.fields2}><button className={locale==='mn'?styles.primary:styles.secondary} onClick={()=>setLocale('mn')}><Languages size={15}/>Монгол</button><button className={locale==='en'?styles.primary:styles.secondary} onClick={()=>setLocale('en')}><Languages size={15}/>English</button><button className={theme==='light'?styles.primary:styles.secondary} onClick={()=>setTheme('light')}><Sun size={15}/>Light</button><button className={theme==='dark'?styles.primary:styles.secondary} onClick={()=>setTheme('dark')}><Moon size={15}/>Dark</button></div><div className={styles.notice}>{text('Сонголт browser дээр хадгалагдаж, дараагийн нэвтрэлтээр хэвээр байна.','Your preference is saved in the browser and restored on the next visit.')}</div></div>}
   {tab==='NOTIFY'&&<div className={styles.grid}><h2>{text('Мэдэгдэл','Notifications')}</h2><Toggle label={text('Төлбөрийн төлөв','Payment status')} value={notifyPayment} set={setNotifyPayment}/><Toggle label={text('Account / billing issue','Account / billing issues')} value={notifyMeta} set={setNotifyMeta}/><Toggle label={text('Долоо хоногийн тайлан','Weekly report')} value={notifyReport} set={setNotifyReport}/><button className={styles.primary} onClick={saveNotifications}><Save size={15}/>{text('Хадгалах','Save')}</button></div>}
   {tab==='PRIVACY'&&<div className={styles.grid}><h2>{text('Нууцлал','Privacy')}</h2><a className={styles.secondary} href="/privacy">{text('Нууцлалын бодлого','Privacy policy')}</a><a className={styles.secondary} href="/data-deletion">{text('Мэдээлэл устгах','Data deletion')}</a><a className={styles.secondary} href="/terms">{text('Үйлчилгээний нөхцөл','Terms of service')}</a></div>}
   {tab==='BILLING'&&<div className={styles.grid}><h2>{text('Төлбөр','Billing')}</h2><p className={styles.muted}>{text('Үйлчилгээний шимтгэл болон transaction history.','Service fees and transaction history.')}</p><a className={styles.primary} href="/payments">{text('Төлбөрийн төв','Billing center')}</a><a className={styles.secondary} href="/transactions">{text('Гүйлгээний түүх','Transaction history')}</a></div>}
   {tab==='ADMIN'&&<div className={styles.grid}><h2>Admin</h2><p className={styles.muted}>{text('Owner/Admin: шимтгэл, webhook, audit log, production readiness.','Owner/Admin: fees, webhooks, audit logs and production readiness.')}</p><a className={styles.primary} href="/admin">Admin Console</a></div>}
  </section><aside className={styles.card}><h3>BOOST.MN</h3><div className={styles.summary} style={{marginTop:12}}><div><span>Account</span><b>{email||'—'}</b></div><div><span>{text('Бизнес','Business')}</span><b>{business||text('Тохируулаагүй','Not set')}</b></div><div><span>{text('Хэл','Language')}</span><b>{locale.toUpperCase()}</b></div><div><span>Theme</span><b>{theme}</b></div><div><span>{text('Сувгууд','Channels')}</span><b><a href="/connections">{text('Шалгах','Review')} →</a></b></div></div></aside></div>}
 </AppShell>
}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:14,padding:'12px 0',borderBottom:'1px solid var(--border)',fontSize:11,fontWeight:700}}><span>{label}</span><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)} style={{width:18,height:18,accentColor:'var(--primary)'}}/></label>}
