import { Body, Controller, Get, Param, Post, Query, Req, Res, UnauthorizedException } from '@nestjs/common'
import { randomBytes, timingSafeEqual } from 'crypto'
import { MetaReadinessService } from './meta-readiness.service'
import { MetaService } from './meta.service'
import { TenantService } from './tenant.service'

@Controller('meta')
export class MetaController {
  private readonly stateCookie = 'ab_meta_oauth_state'
  constructor(private readonly meta: MetaService, private readonly tenant: TenantService, private readonly readiness: MetaReadinessService) {}
  private getCookie(req:any,name:string){const h=String(req?.headers?.cookie||'');const p=h.split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith(`${name}=`));return p?decodeURIComponent(p.slice(name.length+1)):''}
  private cookieOptions(maxAge?:number){const production=process.env.NODE_ENV==='production'||Boolean(process.env.VERCEL);return{httpOnly:true,secure:production,sameSite:'lax' as const,path:'/',...(maxAge?{maxAge}:{})}}

  @Get('status') status(){return{...this.meta.getStatus(),tenantStorageConfigured:true,authProvider:'supabase'}}
  @Get('session') async session(@Req() req:any){try{const{context,connection,metaToken}=await this.tenant.getConnection(req);if(!connection||!metaToken)return{connected:false,workspaceId:context.workspaceId};return{connected:true,workspaceId:context.workspaceId,profile:{id:connection.meta_user_id,name:connection.meta_user_name},tokenExpiresAt:connection.token_expires_at}}catch(error){if(error instanceof UnauthorizedException)return{connected:false};throw error}}
  @Get('auth/url') async authUrl(@Req() req:any,@Res({passthrough:true}) res:any){const appToken=this.tenant.getAppToken(req);const user=await this.tenant.requireUserByToken(appToken);const state=randomBytes(24).toString('base64url');const payload=this.tenant.encrypt(JSON.stringify({state,appToken,userId:user.id,createdAt:Date.now()}));res.cookie(this.stateCookie,payload,this.cookieOptions(10*60*1000));return this.meta.getLoginUrl(state)}
  @Get('auth/callback') async callback(@Req() req:any,@Res() res:any,@Query('code') code?:string,@Query('state') state?:string,@Query('error') error?:string,@Query('error_description') errorDescription?:string){const frontend=process.env.FRONTEND_ORIGIN||'http://localhost:3000';if(error)return res.redirect(`${frontend}/facebook?error=${encodeURIComponent(errorDescription||error)}`);const encryptedState=this.getCookie(req,this.stateCookie);let stored:any=null;try{stored=JSON.parse(this.tenant.decrypt(encryptedState))}catch{}const expected=String(stored?.state||''),actual=String(state||''),fresh=Number(stored?.createdAt||0)>Date.now()-10*60*1000;const valid=Boolean(fresh&&expected&&actual&&expected.length===actual.length&&timingSafeEqual(Buffer.from(expected),Buffer.from(actual)));if(!valid||!stored?.appToken||!stored?.userId){res.clearCookie(this.stateCookie,this.cookieOptions());return res.redirect(`${frontend}/facebook?error=${encodeURIComponent('OAuth state шалгалт амжилтгүй боллоо. Дахин холбоно уу.')}`)}try{const user=await this.tenant.requireUserByToken(stored.appToken);if(user.id!==stored.userId)throw new UnauthorizedException('Хэрэглэгчийн session өөрчлөгдсөн байна.');const tokenResult=await this.meta.exchangeCode(code||'');const metaToken=tokenResult?.access_token;if(!metaToken)throw new UnauthorizedException('Meta access token олдсонгүй.');const profile=await this.meta.getMe(metaToken);await this.tenant.saveConnection(stored.appToken,user,metaToken,profile,tokenResult?.expires_in);res.clearCookie(this.stateCookie,this.cookieOptions());return res.redirect(`${frontend}/facebook?connected=1`)}catch(e:any){res.clearCookie(this.stateCookie,this.cookieOptions());return res.redirect(`${frontend}/facebook?error=${encodeURIComponent(e?.message||'Facebook OAuth холболт амжилтгүй боллоо.')}`)}}
  @Post('logout') async logout(@Req() req:any,@Res({passthrough:true}) res:any){res.clearCookie(this.stateCookie,this.cookieOptions());return this.tenant.disconnect(req)}

  @Get('me') async me(@Req() req:any){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getMe(metaToken)}
  @Get('pages') async pages(@Req() req:any){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getPages(metaToken)}
  @Get('ad-accounts') async adAccounts(@Req() req:any){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getAdAccounts(metaToken)}
  @Get('pages/:pageId/posts') async posts(@Req() req:any,@Param('pageId') pageId:string){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getPagePosts(pageId,metaToken)}
  @Get('pages/:pageId/lead-forms') async leadForms(@Req() req:any,@Param('pageId') pageId:string){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getLeadForms(pageId,metaToken)}
  @Get('pages/:pageId/instagram') async instagram(@Req() req:any,@Param('pageId') pageId:string){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getInstagramIdentity(pageId,metaToken)}
  @Get('targeting/interests') async interests(@Req() req:any,@Query('q') q=''){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.searchInterests(metaToken,q)}

  @Get('ad-accounts/:adAccountId/campaigns') async campaigns(@Req() req:any,@Param('adAccountId') id:string){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getCampaigns(id,metaToken)}
  @Get('ad-accounts/:adAccountId/adsets') async adsets(@Req() req:any,@Param('adAccountId') id:string){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getAdSets(id,metaToken)}
  @Get('ad-accounts/:adAccountId/ads') async ads(@Req() req:any,@Param('adAccountId') id:string){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getAds(id,metaToken)}
  @Get('ad-accounts/:adAccountId/pixels') async pixels(@Req() req:any,@Param('adAccountId') id:string){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getPixels(id,metaToken)}
  @Get('ad-accounts/:adAccountId/custom-audiences') async audiences(@Req() req:any,@Param('adAccountId') id:string){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getCustomAudiences(id,metaToken)}

  @Post('ad-accounts/:adAccountId/campaigns') async createCampaign(@Req() req:any,@Param('adAccountId') id:string,@Body() body:any){const{metaToken,context}=await this.tenant.requireMetaToken(req);const result=await this.meta.createCampaign(id,metaToken,body);await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.campaign.created','campaign',result?.id||null,{adAccountId:id,name:body?.name,status:'PAUSED'});return result}
  @Post('ad-accounts/:adAccountId/adsets') async createAdSet(@Req() req:any,@Param('adAccountId') id:string,@Body() body:any){const{metaToken,context}=await this.tenant.requireMetaToken(req);const result=await this.meta.createAdSet(id,metaToken,body);await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.adset.created','adset',result?.id||null,{adAccountId:id,campaignId:body?.campaignId,status:'PAUSED'});return result}
  @Post('ad-accounts/:adAccountId/creatives/existing-post') async createExistingCreative(@Req() req:any,@Param('adAccountId') id:string,@Body() body:any){const{metaToken,context}=await this.tenant.requireMetaToken(req);const result=await this.meta.createExistingPostCreative(id,metaToken,body);await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.creative.created','creative',result?.id||null,{adAccountId:id,kind:'existing-post'});return result}
  @Post('ad-accounts/:adAccountId/creatives/manual') async createManualCreative(@Req() req:any,@Param('adAccountId') id:string,@Body() body:any){const{metaToken,context}=await this.tenant.requireMetaToken(req);const result=await this.meta.createManualCreative(id,metaToken,body);await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.creative.created','creative',result?.id||null,{adAccountId:id,kind:body?.format||'IMAGE'});return result}
  @Post('ad-accounts/:adAccountId/ads') async createAd(@Req() req:any,@Param('adAccountId') id:string,@Body() body:any){const{metaToken,context}=await this.tenant.requireMetaToken(req);const result=await this.meta.createAd(id,metaToken,body);await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.ad.created','ad',result?.id||null,{adAccountId:id,adSetId:body?.adSetId,status:'PAUSED'});return result}

  @Post('objects/:objectId/update') async updateObject(@Req() req:any,@Param('objectId') objectId:string,@Body() body:any){const{metaToken,context}=await this.tenant.requireMetaToken(req);const result=await this.meta.updateObject(objectId,metaToken,body);await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.object.updated','meta_object',objectId,{fields:Object.keys(body||{})});return result}
  @Post('objects/:objectId/status') async updateStatus(@Req() req:any,@Param('objectId') objectId:string,@Body() body:{status:'ACTIVE'|'PAUSED'}){const{metaToken,context}=await this.tenant.requireMetaToken(req);if(body.status==='ACTIVE'){try{const account=await this.readiness.assertCanActivate(metaToken,objectId);await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.activation_guard.passed','meta_object',objectId,{adAccountId:account.accountId,accountStatus:account.accountStatusLabel,billingState:account.billingState})}catch(error:any){await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.activation_guard.blocked','meta_object',objectId,{reason:error?.response?.code||error?.response?.message||error?.message||'BILLING_NOT_READY',requestedStatus:'ACTIVE'});throw error}}const result=await this.meta.updateStatus(objectId,metaToken,body.status);await this.tenant.writeAudit(context.appToken,context.workspaceId,context.user.id,'meta.status.updated','meta_object',objectId,{status:body.status});return result}
  @Get('ad-accounts/:adAccountId/insights') async insights(@Req() req:any,@Param('adAccountId') id:string,@Query('date_preset') preset='last_7d',@Query('level') level='campaign'){const{metaToken}=await this.tenant.requireMetaToken(req);return this.meta.getInsights(id,metaToken,preset,level)}
}
