'use client'

import { useEffect, useMemo, useState } from 'react'
import { Pause, Play, RefreshCw, Save } from 'lucide-react'
import AppShell from '../../components/layout/AppShell'
import { apiFetch } from '../../lib/api'
import styles from '../manager.module.css'

type Account={id:string;account_id:string;name:string;currency:string}
type Row={id:string;name:string;status?:string;effective_status?:string;campaign_id?:string;adset_id?:string;daily_budget?:string;lifetime_budget?:string;optimization_goal?:string;bid_strategy?:string;creative?:{id?:string;name?:string;thumbnail_url?:string}}

export default function AdsManagerPage(){
 const [accounts,setAccounts]=useState<Account[]>([]),[accountId,setAccountId]=useState(''),[tab,setTab]=useState<'campaigns'|'adsets'|'ads'>('campaigns'),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[editing,setEditing]=useState<Row|null>(null),[busy,setBusy]=useState('')
 useEffect(()=>{apiFetch<any>('/meta/ad-accounts').then(r=>{const a=r?.data||[];setAccounts(a);setAccountId(a[0]?.account_id||a[0]?.id||'')}).catch((e:any)=>{setError(e?.message||'Ad Account авч чадсангүй.');setLoading(false)})},[])
 async function load(){if(!accountId)return;setLoading(true);setError('');try{const r=await apiFetch<any>(`/meta/ad-accounts/${accountId}/${tab}`);setRows(r?.data||[])}catch(e:any){setError(e?.message||'Meta data ачаалж чадсангүй.')}finally{setLoading(false)}}
 useEffect(()=>{if(accountId)load()},[accountId,tab])
 async function status(row:Row,value:'ACTIVE'|'PAUSED'){setBusy(row.id);setError('');try{await apiFetch(`/meta/objects/${row.id}/status`,{method:'POST',body:JSON.stringify({status:value})});await load()}catch(e:any){setError(e?.message||'Status шинэчилж чадсангүй.')}finally{setBusy('')}}
 async function save(){if(!editing)return;setBusy(editing.id);setError('');try{const body:any={name:editing.name};if(tab!=='ads'){if(editing.daily_budget)body.daily_budget=editing.daily_budget;if(editing.lifetime_budget)body.lifetime_budget=editing.lifetime_budget;if(editing.bid_strategy)body.bid_strategy=editing.bid_strategy;if(tab==='adsets'&&editing.optimization_goal)body.optimization_goal=editing.optimization_goal}await apiFetch(`/meta/objects/${editing.id}/update`,{method:'POST',body:JSON.stringify(body)});setEditing(null);await load()}catch(e:any){setError(e?.message||'Шинэчилж чадсангүй.')}finally{setBusy('')}}
 const visible=useMemo(()=>rows.filter(r=>!query||r.name?.toLowerCase().includes(query.toLowerCase())),[rows,query])
 return <AppShell title="Ads Manager" subtitle="Campaign → Ad Set → Ad түвшинд Meta объектуудаа бодитоор удирдана.">
  <div className={styles.card}><div className={styles.toolbar}><div className={styles.actions}><label className={styles.field} style={{minWidth:260}}><span>Ad Account</span><select value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.account_id||a.id}>{a.name} · {a.currency}</option>)}</select></label><label className={styles.field} style={{minWidth:220}}><span>Хайх</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Нэрээр хайх..."/></label></div><div className={styles.actions}><button className={styles.secondary} onClick={load}><RefreshCw size={15}/> Шинэчлэх</button><a className={styles.primary} href="/boost/create">Шинэ зар</a></div></div>
   <div className={styles.tabs}>{(['campaigns','adsets','ads'] as const).map(x=><button key={x} className={tab===x?styles.tabActive:''} onClick={()=>setTab(x)}>{x==='campaigns'?'Campaigns':x==='adsets'?'Ad Sets':'Ads'}</button>)}</div>
   {error&&<div className={styles.error} style={{marginTop:12}}>{error}</div>}
   {loading?<div className={styles.empty}>Meta {tab} ачаалж байна…</div>:visible.length?<div className={styles.tableWrap} style={{marginTop:14}}><table className={styles.table}><thead><tr><th>Нэр</th><th>Төлөв</th><th>{tab==='ads'?'Creative':'Budget'}</th><th>{tab==='campaigns'?'Objective/Bid':tab==='adsets'?'Optimization':'Parent'}</th><th>Үйлдэл</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><b>{r.name}</b><div className={styles.muted}>{r.id}</div></td><td><span className={`${styles.badge} ${(r.effective_status||r.status)==='ACTIVE'?styles.good:styles.warn}`}>{r.effective_status||r.status||'—'}</span></td><td>{tab==='ads'?(r.creative?.name||r.creative?.id||'—'):(r.daily_budget?`Daily ${r.daily_budget}`:r.lifetime_budget?`Lifetime ${r.lifetime_budget}`:'—')}</td><td>{tab==='campaigns'?(r.bid_strategy||'—'):tab==='adsets'?(r.optimization_goal||r.bid_strategy||'—'):(r.adset_id||r.campaign_id||'—')}</td><td><div className={styles.actions}><button className={styles.secondary} onClick={()=>setEditing({...r})}>Засах</button>{(r.effective_status||r.status)==='ACTIVE'?<button className={styles.secondary} disabled={busy===r.id} onClick={()=>status(r,'PAUSED')}><Pause size={14}/> Pause</button>:<button className={styles.primary} disabled={busy===r.id} onClick={()=>status(r,'ACTIVE')}><Play size={14}/> Active</button>}</div></td></tr>)}</tbody></table></div>:<div className={styles.empty}>Объект алга.</div>}
  </div>
  {editing&&<section className={styles.card} style={{marginTop:14}}><h2>{tab==='campaigns'?'Campaign':tab==='adsets'?'Ad Set':'Ad'} засах</h2><div className={styles.grid}><label className={styles.field}><span>Нэр</span><input value={editing.name||''} onChange={e=>setEditing({...editing,name:e.target.value})}/></label>{tab!=='ads'&&<div className={styles.fields2}><label className={styles.field}><span>Daily budget (minor unit)</span><input value={editing.daily_budget||''} onChange={e=>setEditing({...editing,daily_budget:e.target.value})}/></label><label className={styles.field}><span>Lifetime budget (minor unit)</span><input value={editing.lifetime_budget||''} onChange={e=>setEditing({...editing,lifetime_budget:e.target.value})}/></label></div>}{tab==='adsets'&&<div className={styles.fields2}><label className={styles.field}><span>Optimization goal</span><input value={editing.optimization_goal||''} onChange={e=>setEditing({...editing,optimization_goal:e.target.value})}/></label><label className={styles.field}><span>Bid strategy</span><input value={editing.bid_strategy||''} onChange={e=>setEditing({...editing,bid_strategy:e.target.value})}/></label></div>}<div className={styles.actions}><button className={styles.primary} onClick={save} disabled={busy===editing.id}><Save size={15}/> Хадгалах</button><button className={styles.secondary} onClick={()=>setEditing(null)}>Болих</button></div></div></section>}
 </AppShell>
}
